package com.lwm.springcloud.entities;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class User {
    public User() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.accountnum
     *
     * @mbggenerated
     */
    private Integer accountnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.win
     *
     * @mbggenerated
     */
    private Integer win;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.game_match
     *
     * @mbggenerated
     */
    private Integer gameMatch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_day
     *
     * @mbggenerated
     */
    private Date registerDay;


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.accountnum
     *
     * @return the value of user.accountnum
     *
     * @mbggenerated
     */
    public Integer getAccountnum() {
        return accountnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.accountnum
     *
     * @param accountnum the value for user.accountnum
     *
     * @mbggenerated
     */
    public void setAccountnum(Integer accountnum) {
        this.accountnum = accountnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school
     *
     * @return the value of user.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school
     *
     * @param school the value for user.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwd
     *
     * @return the value of user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwd
     *
     * @param pwd the value for user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.integral
     *
     * @return the value of user.integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.integral
     *
     * @param integral the value for user.integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade
     *
     * @return the value of user.grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.win
     *
     * @return the value of user.win
     *
     * @mbggenerated
     */
    public Integer getWin() {
        return win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.win
     *
     * @param win the value for user.win
     *
     * @mbggenerated
     */
    public void setWin(Integer win) {
        this.win = win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.game_match
     *
     * @return the value of user.game_match
     *
     * @mbggenerated
     */
    public Integer getGameMatch() {
        return gameMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.game_match
     *
     * @param gameMatch the value for user.game_match
     *
     * @mbggenerated
     */
    public void setGameMatch(Integer gameMatch) {
        this.gameMatch = gameMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_day
     *
     * @return the value of user.register_day
     *
     * @mbggenerated
     */
    public Date getRegisterDay() {
        return registerDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_day
     *
     * @param registerDay the value for user.register_day
     *
     * @mbggenerated
     */
    public void setRegisterDay(Date registerDay) {
        this.registerDay = registerDay;
    }
    
    public User(Integer accountnum, String nickname, String school, String password, Integer integral, String grade,
			Integer win, Integer match,Date registerday) {
		super();
		this.accountnum = accountnum;
		this.nickname = nickname;
		this.school = school;
		this.pwd = password;
		this.integral = integral;
		this.grade = grade;
		this.win = win;
		this.gameMatch = match;
		this.registerDay=registerday;
	}
    public User(Integer accountnum, String nickname, String school, String password, Integer integral, String grade,
			Integer win, Integer match,java.sql.Date registerday) {
		super();
		this.accountnum = accountnum;
		this.nickname = nickname;
		this.school = school;
		this.pwd = password;
		this.integral = integral;
		this.grade = grade;
		this.win = win;
		this.gameMatch = match;
		this.registerDay=new Date(registerday.getTime());
	}
} 