package com.lwm.springcloud.entities;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table video
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_address
     *
     * @mbggenerated
     */
    private String videoAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.img_address
     *
     * @mbggenerated
     */
    private String imgAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.duration
     *
     * @mbggenerated
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.view
     *
     * @mbggenerated
     */
    private Integer view;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.discription
     *
     * @mbggenerated
     */
    private String discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.title
     *
     * @return the value of video.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.title
     *
     * @param title the value for video.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_address
     *
     * @return the value of video.video_address
     *
     * @mbggenerated
     */
    public String getVideoAddress() {
        return videoAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_address
     *
     * @param videoAddress the value for video.video_address
     *
     * @mbggenerated
     */
    public void setVideoAddress(String videoAddress) {
        this.videoAddress = videoAddress == null ? null : videoAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.img_address
     *
     * @return the value of video.img_address
     *
     * @mbggenerated
     */
    public String getImgAddress() {
        return imgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.img_address
     *
     * @param imgAddress the value for video.img_address
     *
     * @mbggenerated
     */
    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress == null ? null : imgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.duration
     *
     * @return the value of video.duration
     *
     * @mbggenerated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.duration
     *
     * @param duration the value for video.duration
     *
     * @mbggenerated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.view
     *
     * @return the value of video.view
     *
     * @mbggenerated
     */
    public Integer getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.view
     *
     * @param view the value for video.view
     *
     * @mbggenerated
     */
    public void setView(Integer view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.discription
     *
     * @return the value of video.discription
     *
     * @mbggenerated
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.discription
     *
     * @param discription the value for video.discription
     *
     * @mbggenerated
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }
}